Repository acm-ucr/developer-station, pull requests merged in 2024-10, with the labels that each got.

#17 Rattahamberg/courses layout
  src/components/courselayout.tsx
  tailwind.config.ts
Labels: ready for review

#16 darsh175223/try course button
  src/app/page.tsx
  src/components/courselearn.tsx
  src/components/try-course-button.tsx
  tailwind.config.ts
Labels: ready for review

#14 About Name component
  src/app/page.tsx
  src/components/home/about.tsx
Labels: ready for review, changes requested

#19 Short Course Description
  src/components/short_course_description.tsx
  tailwind.config.ts
Labels: do not merge, ready for review, changes requested

#18 Created prototype for Course Timeline component
  src/components/courseTimeline.tsx
  tailwind.config.ts
Labels: ready for review

#20 Projects Header
  public/images/Projectshome1.webp
  src/app/projects/page.tsx
  src/components/ProjectsHeader.tsx
  tailwind.config.ts
Labels: ready for review

#13 Created the ProjectCard component
  src/components/home/ProjectCard.tsx
  tailwind.config.ts
Labels: ready for review

#15 Created Course Name Component
  next.config.js
  src/app/course/[name]/page.tsx
  src/app/course/page.tsx
  src/components/course/layout.tsx
  src/components/course/learn.tsx
  src/components/course/name.tsx
  src/components/course/timeline.tsx
  src/courses/index.tsx
Labels: do not merge, changes requested
